`r if (knitr:::is_html_output()) '
# Declaration{-}
'`
`r if (knitr:::is_latex_output()) '
# Declaration {.unlisted .unnumbered}
'`

I hereby declare that this dissertation is all my own original work and that all sources have been acknowledged. It is xxx words in length.

`r if (knitr:::is_html_output()) '
# Acknowledgements{-}
'`
`r if (knitr:::is_latex_output()) '
# Acknowledgements {.unlisted .unnumbered}
'`

I would like to thank my supervisor and those who supported this dissertation.

```{=latex}
\setcounter{tocdepth}{3}
\tableofcontents
\listoffigures
\listoftables
```

`r if (knitr:::is_html_output()) '
# Abbreviations{-}
'`
`r if (knitr:::is_latex_output()) '
# Abbreviations {.unlisted .unnumbered}
'`

| Term | Definition |
| ---- | ---------- |
| AIS | Automatic Identification System |
| AOI | Area of Interest |
| EIA | U.S. Energy Information Administration |
| GAT | Graph Attention Network |
| GFW | Global Fishing Watch |
| IMF | International Monetary Fund |
| RMSE | Root Mean Squared Error |
| SAR | Synthetic Aperture Radar |
| SHAP | SHapley Additive exPlanations |
| TCN | Temporal Convolutional Network |
| VIIRS | Visible Infrared Imaging Radiometer Suite |
| WTI | West Texas Intermediate |
| XAttn | Cross-attention |
| XGBoost | Extreme Gradient Boosting |
